#############
### build ###
#############

# base image
FROM node:12.14.0 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@9.1.1 --unsafe

# add app
COPY . /app

# generate build
RUN ng build ---prod --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.17.9-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# copy additional nginx configuration file for the front end to serve as a backend proxy
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/ssl /etc/nginx/ssl

# expose port 80
EXPOSE 80
EXPOSE 443

# run nginx
CMD ["nginx", "-g", "daemon off;"]