apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordsfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recordsfrontend
  template:
    metadata:
      labels:
        app: recordsfrontend
    spec:
      containers:
        - name: recordsfrontendcontainer
          image: recordsfrontend:0.3
          ports:
            - containerPort: 80
            - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: recordsfrontend
spec:
  selector:
    app: recordsfrontend
  ports:
    - name: frontend
      protocol: TCP
      port: 9080
      targetPort: 80
    - name: frontendssl
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
