apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordsfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recordsfrontend
  template:
    metadata:
      labels:
        app: recordsfrontend
    spec:
      containers:
        - name: recordsfrontendcontainer
          image: recordsfrontend:0.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: recordsfrontend
spec:
  selector:
    app: recordsfrontend
  ports:
    - port: 9080
      targetPort: 80
  type: LoadBalancer
